name: Build .NET Framework 4.8 App

on:
  push:
    branches:
      - none

  workflow_dispatch:  # Enables manual trigger

jobs:
  build:
    runs-on: windows-latest   # .NET Framework requires Windows

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup MSBuild (Visual Studio Build Tools)
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Step 3: Setup NuGet
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      # Step 4: Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore FileUploadwithModelandPreview/FileUploadwithModelandPreview.sln

      # Step 5: Build the solution
      - name: Build Solution
        run: msbuild FileUploadwithModelandPreview/FileUploadwithModelandPreview.sln /p:Configuration=Release /p:Platform="Any CPU"

      # Step 6: (Optional) Package Web App (if it's a web project)
      - name: Package Web App
        run: msbuild FileUploadwithModelandPreview/FileUploadwithModelandPreview.csproj /p:Configuration=Release /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="${{ github.workspace }}\\drop\\WebApp.zip"

      # Step 7: Upload artifact (output files)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: ${{ github.workspace }}\drop
