name: Build .NET Framework 4.8 WebApp

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Show repository structure
        run: |
          echo "Current workspace: ${{ github.workspace }}"
          dir ${{ github.workspace }} -Recurse

      - name: Restore NuGet packages
        run: nuget restore FileUploadwithModelandPreview/FileUploadwithModelandPreview.sln

      - name: Build Solution
        run: msbuild FileUploadwithModelandPreview/FileUploadwithModelandPreview.sln /p:Configuration=Release

      - name: Package Web App
        run: |
          msbuild FileUploadwithModelandPreview/FileUploadwithModelandPreview/FileUploadwithModelandPreview.csproj `
            /p:Configuration=Release `
            /p:DeployOnBuild=true `
            /p:WebPublishMethod=Package `
            /p:PackageAsSingleFile=true `
            /p:PackageLocation="${{ github.workspace }}\\drop"

      - name: Verify drop folder
        run: dir "${{ github.workspace }}\drop"

      - name: Upload Artifact (WebApp.zip)
        uses: actions/upload-artifact@v4
        with:
          name: WebApp
          path: ${{ github.workspace }}\drop
