name: Build and Deploy .NET Framework 4.8 WebApp (FileUploadwithModel)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1️⃣ Install latest NuGet
      - name: Install NuGet
        uses: NuGet/setup-nuget@v1
        with:
          nuget-version: 'latest'
          
      # 2️⃣ Restore NuGet packages   
      - name: Restore NuGet Packages
        run: nuget restore FileUploadwithModelandPreview/FileUploadwithModelandPreview.sln

      # 3️⃣ Build using Visual Studio (MSBuild)  
      - name: Build Solution
        run: msbuild FileUploadwithModelandPreview/FileUploadwithModelandPreview.sln ^
          /p:Configuration=Release ^
          /p:DeployOnBuild=true ^
          /p:WebPublishMethod=FileSystem ^
          /p:PackageAsSingleFile=false ^
          /p:SkipInvalidConfigurations=true ^
          /p:PackageLocation="${{ github.workspace }}\Package"

      # 4️⃣ Debug - show where web.config and publish folders exist
      - name: Locate publish output
        shell: pwsh
        run: |
            Write-Host "=== Searching for web.config and publish folders ==="
            Get-ChildItem "${{ github.workspace }}" -Recurse -Filter "web.config" | ForEach-Object {
            Write-Host "Found web.config at: $($_.Directory.FullName)"
            }
      # 5️⃣ Copy publish output (detects PackageTmp or bin\Release)
      - name: Copy publish output to artifact staging directory
        shell: pwsh
        run: |
          $srcCandidates = @(
            "${{ github.workspace }}\FileUploadwithModelandPreview\FileUploadwithModelandPreview\obj\Release\Package\PackageTmp",
            "${{ github.workspace }}\FileUploadwithModelandPreview\FileUploadwithModelandPreview\bin\Release"
          )
      
          $dst = "${{ github.workspace }}\WebApp"
          New-Item -ItemType Directory -Force -Path $dst | Out-Null
      
          $found = $false
          foreach ($src in $srcCandidates) {
            if (Test-Path $src) {
              Write-Host "✅ Found publish folder at: $src"
              Copy-Item -Path "$src\*" -Destination $dst -Recurse -Force
              $found = $true
              break
            }
          }
      
          if (-not $found) {
            Write-Host "⚠️ No publish output found. Check build step above for errors."
            exit 1
          }
          
      # 6️⃣ Verify artifact folder contents
      - name: List Artifact Staging Directory
        shell: pwsh
        run: |
          Write-Host "=== Contents of ${{ github.workspace }}\WebApp ==="
          Get-ChildItem "${{ github.workspace }}\WebApp" -Recurse

      
      # 7️⃣ Publish artifact for deployment
      - name: Publish Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: WebApp


